#
# <meta:header>
#   <meta:licence>
#     Copyright (c) 2025, Manchester University (http://www.manchester.ac.uk/)
#
#     This work is made available under the Creative Commons
#     Attribution-ShareAlike 4.0 International licence.
#
#     For details of the licence terms see:
#     https://creativecommons.org/licenses/by-sa/4.0/
#   </meta:licence>
# </meta:header>
#
# AIMetrics: [
#     {
#     "name": "ChatGPT",
#     "contribution": {
#       "value": 5,
#       "units": "%"
#       }
#     }
#   ]
#

openapi: 3.1.0
info:
  title: IVOA ExecutionBroker simple compute resource
  version: "1.0"
  summary: IVOA ExecutionBroker simple compute resource
  description: >-
    OpenAPI schema for a simple compute resource in IVOA ExecutionBroker
  contact:
    name: Dave Morris
    url: https://github.com/Zarquan
  license:
    name: Creative Commons Attribution Share Alike 4.0 International
    identifier: CC-BY-SA-4.0

components:
  schemas:

    SimpleComputeResource:
      type: object
      name:  SimpleComputeResource
      title: SimpleComputeResource
      description: >-
        A simple compute resource.
      allOf:
        - $ref: '../../components.yaml#/components/schemas/AbstractComputeResource'
        - type: object
          properties:
            cores:
              $ref: 'SimpleComputeCores'
            memory:
              $ref: 'SimpleComputeMemory'
            volumes:
              description: >-
                A list of the filesystem volumes to mount.
              type: array
              items:
                type: string

    SimpleComputeCores:
      description: >-
        The number of CPU cores requested by the user.
        The minimum represents the lower limit that the excution requires.
        The maximum represents the highest number of cores that the excution can use.
      type: object
      title: SimpleComputeCores
#     allOf:
#       - $ref: '../../../components/utils.yaml#/components/schemas/MinMaxLong'
#       - $ref: 'SimpleMinMaxLong'
#       - type: object
      properties:
        min:
          type: integer
          format: int64
        max:
          type: integer
          format: int64

    SimpleComputeMemory:
      description: >-
        The amount of memory requested by the user.
        The minimum represents the lower limit that the excution requires.
        The maximum represents the highest amount of memory that the excution can use.
        All values are given in multiples of 'GiB'.
      type: object
      title: SimpleComputeMemory
      properties:
        min:
          type: integer
          format: int64
        max:
          type: integer
          format: int64
#       units:
#         $ref: '../../../components/utils.yaml#/components/schemas/ComputeUnitsEnum'


